### ISSUE TITLE
Custom Extensions

### ISSUE THREAD

**Issue by xcool456** [sibiraj-s/marked-react#26]
Thx for lib. 
How can i add a custom extension? 
In "marked" lib i can use marked.use().

**Comment by sibiraj-s** [comment]
I had plans to add support, but not all marked extensions are compatible, most extensions transform the content into raw html string which won't work with react. 

Open to suggestions.

**Comment by xcool456** [comment]
I added extension functionality for my project. Testing only with katex library.

Markdown:
![image](https://github.com/sibiraj-s/marked-react/assets/39434819/4f80067f-76d1-40bd-b659-d3206d53497a)

ReactParser:
parse
![image](https://github.com/sibiraj-s/marked-react/assets/39434819/8e2e63d0-39f9-4578-a9d0-29778413957c)
parseInline
![image](https://github.com/sibiraj-s/marked-react/assets/39434819/40c359ea-0ed8-4c76-a2e7-f8be7392a845)

ReactRenderer:
![image](https://github.com/sibiraj-s/marked-react/assets/39434819/77338bd1-7e3d-4d0f-9ab0-ec860f14b0aa)

Maybe my code will be usefull

**Comment by sibiraj-s** [comment]
I kinda had the same implementation, event started the work, Even now the component accepts the marked instance, `<Markdown instance={new Marked()}/>` which should support some extensions, but not documented since it is not tested extensively.

but I am just hesitant from using the dangerousHTML implementation. considering if it could be handled better, but couldn't find enough time to work on it.
